---
# Play
- hosts: role_dns
  tasks:
    - name: add repository HAproxy
      apt_repository:
        repo: ppa:vbernat/haproxy-1.7
        state: present
    - name: install haproxy
      apt:
        name:
          - haproxy
    - name: configure haproxy
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        block: |
          frontend http_front
            bind *:80
            stats uri /haproxy?stats
            default_backend http_back

          backend http_back
            balance roundrobin
            server s1 192.168.50.20:80 check
            server s2 192.168.50.30:80 check
    - name: restart haproxy
      service:
        name: "haproxy"
        state: restarted
- hosts: role_db
  tasks:
    - name: add repository mariadb
      apt_repository:
        repo: ppa:vbernat/haproxy-1.7
        state: present
- hosts: role_nfs
  tasks:
    - name: install nfs
      apt:
        name=nfs-kernel-server
    - name: Create mountable dir
      file:
        path=/share
        state=directory
        mode=777
        owner=root
        group=root
    - name: bind volume
      mount:
        path: /share
        src: /home/data
        opts: bind
        state: mounted
        fstype: none

    - name: Ensure NFS utilities are installed.
      apt:
        name={{ item }}
        state=present
        update_cache=yes
      loop:
        - nfs-common
        - nfs-kernel-server

    - name: copy /etc/exports
      template:
        src=templates/exports.j2
        dest=/etc/exports
        owner=root
        group=root
    - name: restart nfs
      service:
        name=nfs-kernel-server
        state=restarted
- hosts: role_apache
  vars_files:
    - vars/default.yml
  tasks:
    - name: install php apache
      apt:
        name:
          - php7.3
          - apache2
    - name: Install PHP Extensions
      apt: name={{ item }}
        update_cache=yes
        state=latest
      loop: "{{ php_modules }}"
    - name: Ensure NFS common is installed.
      apt:
        name=nfs-common
        state=installed
        update_cache=yes

    - name: Create mountable dir
      file:
        path=/mnt/nfs
        state=directory
        mode=777
        owner=root
        group=root
    - name: set mountpoints
      mount:
        name=/mnt/nfs
        src=192.168.50.50:/share
        fstype=nfs
        opts=rw,sync,hard,intr
        state=mounted
