---
# Play
- hosts: role_apache
  tasks:
  - name: install php apache
    apt:
      name:
        - php7.3
        - apache2
- hosts: role_dns
  tasks:
  - name: add repository HAproxy
    apt_repository:
      repo: ppa:vbernat/haproxy-1.7
      state: present
  - name: install haproxy
    apt:
      name:
        - haproxy
  - name: configure haproxy
    blockinfile:
      path: /etc/haproxy/haproxy.cfg
      block: |
        frontend http_front
          bind *:80
          stats uri /haproxy?stats
          default_backend http_back

        backend http_back
          balance roundrobin
          server s1 192.168.50.20:80 check
          server s2 192.168.50.30:80 check
  - name: restart haproxy
    service:
      name: "haproxy"
      state: restarted
- hosts: role_db
  - name: add repository mariadb
    apt_repository:
      repo: ppa:vbernat/haproxy-1.7
      state: present
  - name: install mariadb
    roles:
      { role: adfinis-sygroup.mariadb }
- hosts: role_nfs
  tasks:
    - name: Create mountable dir
      file:
        path=/share
        state=directory
        mode=777
        owner=root
        group=root
    - name: set mountpoints
      mount:
        name=/share
        src=/home/data
        fstype=auto
        opts=defaults,nobootwait
        dump=0
        passno=2
        state=mounted

    - name: Ensure NFS utilities are installed.
      apt:
        name={{ item }}
        state=installed
        update_cache=yes
      with_items:
        - nfs-common
        - nfs-kernel-server

    - name: copy /etc/exports
      template:
        src=templates/exports.j2
        dest=/etc/exports
        owner=root
        group=root

    - name: restart nfs server
      service:
        name=nfs-kernel-server
        state=restarted

- hosts: role_apache
  tasks:
    - name: Ensure NFS common is installed.
      apt:
        name=nfs-common
        state=installed
        update_cache=yes

    - name: Create mountable dir
      file:
        path=/mnt/nfs
        state=directory
        mode=777
        owner=root
        group=root
    - name: set mountpoints
      mount:
        name=/mnt/nfs
        src={{ hostvars[role_nfs].ipaddress }}:/share
        fstype=nfs
        opts=defaults,nobootwait
        dump=0
        passno=2
        state=mounted
