
---
- hosts: role_apache
  vars_files:
    - vars/default.yml
  tasks:
    - name: mysql 
      apt:
        name:
          - default-mysql-server
          - python3-pymysql    
          - python2.7-mysqldb

    - name: Start mysqld service
      systemd: name=mysqld state=started enabled=yes
 
    - name: Set MySQL root Password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '{{ mysql_root_password }}'
        state: present
 
    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
 
#    - name: Create MySQL user for WordPress
#      mysql_user:
#        name: "{{ mysql_user }}"
#        password: "{{ mysql_password }}"
#        priv: "{{ mysql_db }}.*:ALL"
#        state: present
#        login_user: root
#        login_password: "{{ mysql_root_password }}"

    - name: Start httpd service
      systemd:
        name=apache2
        state=started
        enabled=yes
 
    - name: Create Apache Document Root
      file:
        path: "/var/www/{{ item.name }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop: "{{ virtualhost }}"

    - name: Set up Apache VirtualHost
      template:
        src: "templates/httpd.conf.j2"
        dest: "/etc/apache2/sites-available/{{ item.name }}"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      loop: "{{ virtualhost }}"

    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ item.name }}"
        remote_src: yes
        creates: "/var/www/{{ item.name }}/wordpress"
      loop: "{{ virtualhost }}"

    - name: Update default Apache site
      template:
        src: "templates/site.conf.j2"
        dest: /etc/apache2/sites-enabled/{{ item.conf }}
        owner: root
        group: root
        mode: 0755
      loop: "{{ virtualhost }}"

    - name: Set ownership
      file:
        path: "/var/www/{{ item.name }}"
        state: directory
        recurse: yes
        owner: root
        group: root
      loop: "{{ virtualhost }}"

    - name: Set permissions for wordpress
      file:
        path: "/var/www/{{ item.name }}/wordpress"
        owner: root
        group: root
        mode: 0755
      loop: "{{ virtualhost }}"

    - name: Set permissions for directories
      shell: "/usr/bin/find /var/www/{{ item.name }}/wordpress/ -type d -exec chmod 777 {} \\;"
      loop: "{{ virtualhost }}"
    
    - name: Set permissions for files
      shell: "/usr/bin/find /var/www/{{ item.name }}/wordpress/ -type f -exec chmod 777 {} \\;"
      loop: "{{ virtualhost }}"
 
    - name: Copy sample config file
      command: mv /var/www/{{ item.name }}/wordpress/wp-config-sample.php /var/www/{{ item.name }}/wordpress/wp-config.php creates=/var/www/{{ item.name }}/wordpress/wp-config.php
      become: yes
      loop: "{{ virtualhost }}"

    - name: Update WordPress config file 
      lineinfile:
        dest=/var/www/devops.com/wordpress/wp-config.php
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
      loop:
        - {'regexp': "^define\\( 'DB_NAME', '(.)+' \\);", 'line': "define('DB_NAME', '{{mysql_db}}');"}
        - {'regexp': "^define\\( 'DB_USER', '(.)+' \\);", 'line': "define('DB_USER', '{{mysql_user}}');"}
        - {'regexp': "^define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define('DB_PASSWORD', '{{mysql_password}}');"}
      become: yes

    - name: Update WordPress config file
      lineinfile:
        dest=/var/www/devsec.com/wordpress/wp-config.php
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
      loop:
        - {'regexp': "^define\\( 'DB_NAME', '(.)+' \\);", 'line': "define('DB_NAME', '{{mysql_db}}');"}
        - {'regexp': "^define\\( 'DB_USER', '(.)+' \\);", 'line': "define('DB_USER', '{{mysql_user}}');"}
        - {'regexp': "^define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define('DB_PASSWORD', '{{mysql_password}}');"}
      become: yes

    - name: Update WordPress config file
      lineinfile:
        dest=/var/www/devsecops.com/wordpress/wp-config.php
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
      loop:
        - {'regexp': "^define\\( 'DB_NAME', '(.)+' \\);", 'line': "define('DB_NAME', '{{mysql_db}}');"}
        - {'regexp': "^define\\( 'DB_USER', '(.)+' \\);", 'line': "define('DB_USER', '{{mysql_user}}');"}
        - {'regexp': "^define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define('DB_PASSWORD', '{{mysql_password}}');"}
      become: yes

    - name: restart apache
      systemd: name=apache2 state=restarted
      become: yes
